// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCupPredictor.API.Data;

#nullable disable

namespace WorldCupPredictor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902041613_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("WorldCupPredictor.API.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FlagPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OppCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Fixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BracketSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Matchday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamAId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamBId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("TeamAId");

                    b.HasIndex("TeamBId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Fixtures");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GroupStanding", b =>
                {
                    b.Property<int>("SimulationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Played")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("SimulationRunId", "GroupId", "CountryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupStandings");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GroupTeam", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GroupId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("GroupTeams");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.SimulatedMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FixtureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GoalsB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SimulationRunId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TeamAWinProbability")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("SimulationRunId", "FixtureId")
                        .IsUnique();

                    b.ToTable("SimulatedMatches");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ChampionCountryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampionCountryId");

                    b.HasIndex("TournamentId");

                    b.ToTable("SimulationRuns");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Fixture", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("WorldCupPredictor.API.Models.Country", "TeamA")
                        .WithMany()
                        .HasForeignKey("TeamAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Country", "TeamB")
                        .WithMany()
                        .HasForeignKey("TeamBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Tournament", "Tournament")
                        .WithMany("Fixtures")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("TeamA");

                    b.Navigation("TeamB");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Group", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Tournament", "tournament")
                        .WithMany("Group")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tournament");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GroupStanding", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.SimulationRun", "SimulationRun")
                        .WithMany()
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Group");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.GroupTeam", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.Group", "Group")
                        .WithMany("GroupTeams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.SimulatedMatch", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Fixture", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupPredictor.API.Models.SimulationRun", "SimulationRun")
                        .WithMany("SimulatedMatches")
                        .HasForeignKey("SimulationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");

                    b.Navigation("SimulationRun");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.SimulationRun", b =>
                {
                    b.HasOne("WorldCupPredictor.API.Models.Country", "ChampionCountry")
                        .WithMany()
                        .HasForeignKey("ChampionCountryId");

                    b.HasOne("WorldCupPredictor.API.Models.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChampionCountry");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Group", b =>
                {
                    b.Navigation("GroupTeams");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.SimulationRun", b =>
                {
                    b.Navigation("SimulatedMatches");
                });

            modelBuilder.Entity("WorldCupPredictor.API.Models.Tournament", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
